version: '3'

services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    volumes:
      - pg_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_SECRET}
      - POSTGRES_DB=${DB_NAME}
  api:
    build: ./
    container_name: todo-list-api
    restart: always
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    volumes:
      - ./.env:/app/.env
    environment:
      - TYPEORM_USERNAME=${DB_USER}
      - TYPEORM_PASSWORD=${DB_SECRET}
      - TYPEORM_DATABASE=${DB_NAME}
      - TYPEORM_PORT=5432
      - TYPEORM_HOST=db
      - NODE_PROCESS=production

volumes:
  pg_db_data:
    